# NYC Airbnb — Data Preprocessing

In [1]:
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np

In [2]:
import os
from pathlib import Path

# Ensure the working directory is data/ regardless of where Jupyter was launched.
# Handles VS Code (already sets CWD to notebook folder) and classic Jupyter
# launched from the project root.
for candidate in [Path('.'), Path('data')]:
    if (candidate / 'listings.csv').exists():
        os.chdir(candidate)
        break

print('Working directory:', os.getcwd())

Working directory: /Users/ayushdesai/Documents/Data Science/Machine Learning 2/ds4420_ml2_project/data

## Prepare, explore, and clean data

In [3]:
# Load data
airbnb = pd.read_csv('listings.csv')
airbnb.head(10)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,1274691077561855573,https://www.airbnb.com/rooms/1274691077561855573,20251101201932,2025-11-02,city scrape,Beautiful room for rent hosted by Svitlana,Cozy Room for Rent in a Two-Bedroom Apartment<...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,658783772,...,5.0,5.00,5.00,OSE-STRREG-0002773,f,1,0,1,0,1.62
1,1274722590671904755,https://www.airbnb.com/rooms/1274722590671904755,20251101201932,2025-11-02,city scrape,Exquisite & Charming Studio in Prime Locations,This stylish place to stay is perfect for grou...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,458668555,...,5.0,4.50,5.00,NaN,f,6,0,6,0,0.21
2,1274773188072371454,https://www.airbnb.com/rooms/1274773188072371454,20251101201932,2025-11-02,city scrape,"Private 2 Bedroom Unit, Full Kitchen, Washer/D...",This stylish place to stay is perfect for trav...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,22369387,...,NaN,NaN,NaN,NaN,f,3,2,1,0,NaN
3,1274820999428562667,https://www.airbnb.com/rooms/1274820999428562667,20251101201932,2025-11-02,city scrape,"Beautiful, Serene West Village Treehouse",Switch off in this serene one-bedroom oasis on...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,505544503,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
4,1274826163511555978,https://www.airbnb.com/rooms/1274826163511555978,20251101201932,2025-11-02,city scrape,Renovated 1BR w/ Spa Shower,Newly renovated 1-bedroom oasis in vibrant Dow...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,493151605,...,5.0,4.00,5.00,NaN,f,4,2,2,0,0.10
5,1274909412180886814,https://www.airbnb.com/rooms/1274909412180886814,20251101201932,2025-11-02,city scrape,Urban Oasis Brooklyn,"Modern, Cozy Apartment with Full Amenities in ...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,389495893,...,5.0,4.75,5.00,NaN,f,1,1,0,0,0.55
6,1274943629134607784,https://www.airbnb.com/rooms/1274943629134607784,20251101201932,2025-11-02,city scrape,Female-Shared space -Private room in Queens-JF...,Private room with share bathroom and kitchen i...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,471345215,...,5.0,5.00,5.00,NaN,f,26,2,24,0,0.20
7,1275276318052624457,https://www.airbnb.com/rooms/1275276318052624457,20251101201932,2025-11-02,city scrape,Bedroom in Beautiful Park Slope,Keep it simple at this peaceful and centrally ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,356471612,...,5.0,5.00,4.75,NaN,f,3,1,2,0,0.37
8,1279666081527148590,https://www.airbnb.com/rooms/1279666081527148590,20251101201932,2025-11-02,city scrape,Deluxe Queen – Quiet SoHo Hideaway,NaN,NaN,https://a0.muscache.com/pictures/prohost-api/H...,572984161,...,NaN,NaN,NaN,NaN,t,1,0,1,0,NaN
9,1279668704913671652,https://www.airbnb.com/rooms/1279668704913671652,20251101201932,2025-11-02,previous scrape,Steps From The Dazzling Lights Of Broadway,"Discover an enduring haven for connection, ins...",▶ Activities and cultural attractions <br />— ...,https://a0.muscache.com/pictures/prohost-api/H...,658749694,...,NaN,NaN,NaN,Exempt,t,8,0,8,0,NaN

In [4]:
# Get info on dataset
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36353 entries, 0 to 36352
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            36353 non-null  int64
 1   listing_url                                   36353 non-null  object
 2   scrape_id                                     36353 non-null  int64
 3   last_scraped                                  36353 non-null  object
 4   source                                        36353 non-null  object
 5   name                                          36351 non-null  object
 6   description                                   35178 non-null  object
 7   neighborhood_overview                         18748 non-null  object
 8   picture_url                                   36353 non-null  object
 9   host_id                                       36353 non-null  int64
 10  host_url                                      36353 non-null  object
 11  host_name                                     34896 non-null  object
 12  host_since                                    34896 non-null  object
 13  host_location                                 27234 non-null  object
 14  host_about                                    19483 non-null  object
 15  host_response_time                            20188 non-null  object
 16  host_response_rate                            20188 non-null  object
 17  host_acceptance_rate                          20429 non-null  object
 18  host_is_superhost                             35899 non-null  object
 19  host_thumbnail_url                            34896 non-null  object
 20  host_picture_url                              34896 non-null  object
 21  host_neighbourhood                            27475 non-null  object
 22  host_listings_count                           34896 non-null  float64
 23  host_total_listings_count                     34896 non-null  float64
 24  host_verifications                            34896 non-null  object
 25  host_has_profile_pic                          34896 non-null  object
 26  host_identity_verified                        34896 non-null  object
 27  neighbourhood                                 18749 non-null  object
 28  neighbourhood_cleansed                        36353 non-null  object
 29  neighbourhood_group_cleansed                  36353 non-null  object
 30  latitude                                      36353 non-null  float64
 31  longitude                                     36353 non-null  float64
 32  property_type                                 36353 non-null  object
 33  room_type                                     36353 non-null  object
 34  accommodates                                  36353 non-null  int64
 35  bathrooms                                     21703 non-null  float64
 36  bathrooms_text                                36238 non-null  object
 37  bedrooms                                      30273 non-null  float64
 38  beds                                          21658 non-null  float64
 39  amenities                                     36353 non-null  object
 40  price                                         21415 non-null  object
 41  minimum_nights                                36353 non-null  int64
 42  maximum_nights                                36353 non-null  int64
 43  minimum_minimum_nights                        36350 non-null  float64
 44  maximum_minimum_nights                        36350 non-null  float64
 45  minimum_maximum_nights                        36350 non-null  float64
 46  maximum_maximum_nights                        36350 non-null  float64
 47  minimum_nights_avg_ntm                        36353 non-null  float64
 48  maximum_nights_avg_ntm                        36353 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              30725 non-null  object
 51  availability_30                               36353 non-null  int64
 52  availability_60                               36353 non-null  int64
 53  availability_90                               36353 non-null  int64
 54  availability_365                              36353 non-null  int64
 55  calendar_last_scraped                         36353 non-null  object
 56  number_of_reviews                             36353 non-null  int64
 57  number_of_reviews_ltm                         36353 non-null  int64
 58  number_of_reviews_l30d                        36353 non-null  int64
 59  availability_eoy                              36353 non-null  int64
 60  number_of_reviews_ly                          36353 non-null  int64
 61  estimated_occupancy_l365d                     36353 non-null  int64
 62  estimated_revenue_l365d                       21415 non-null  float64
 63  first_review                                  25007 non-null  object
 64  last_review                                   25007 non-null  object
 65  review_scores_rating                          25007 non-null  float64
 66  review_scores_accuracy                        24997 non-null  float64
 67  review_scores_cleanliness                     25006 non-null  float64
 68  review_scores_checkin                         24993 non-null  float64
 69  review_scores_communication                   25001 non-null  float64
 70  review_scores_location                        24991 non-null  float64
 71  review_scores_value                           24991 non-null  float64
 72  license                                       5274 non-null   object
 73  instant_bookable                              36353 non-null  object
 74  calculated_host_listings_count                36353 non-null  int64
 75  calculated_host_listings_count_entire_homes   36353 non-null  int64
 76  calculated_host_listings_count_private_rooms  36353 non-null  int64
 77  calculated_host_listings_count_shared_rooms   36353 non-null  int64
 78  reviews_per_month                             25007 non-null  float64
dtypes: float64(23), int64(20), object(36)
memory usage: 21.9+ MB

In [5]:
# Check for missing values
missing = airbnb.isnull().sum()
print(missing[missing > 0])

name                               2
description                     1175
neighborhood_overview          17605
host_name                       1457
host_since                      1457
host_location                   9119
host_about                     16870
host_response_time             16165
host_response_rate             16165
host_acceptance_rate           15924
host_is_superhost                454
host_thumbnail_url              1457
host_picture_url                1457
host_neighbourhood              8878
host_listings_count             1457
host_total_listings_count       1457
host_verifications              1457
host_has_profile_pic            1457
host_identity_verified          1457
neighbourhood                  17604
bathrooms                      14650
bathrooms_text                   115
bedrooms                        6080
beds                           14695
price                          14938
minimum_minimum_nights             3
maximum_minimum_nights             3
minimum_maximum_nights             3
maximum_maximum_nights             3
calendar_updated               36353
has_availability                5628
estimated_revenue_l365d        14938
first_review                   11346
last_review                    11346
review_scores_rating           11346
review_scores_accuracy         11356
review_scores_cleanliness      11347
review_scores_checkin          11360
review_scores_communication    11352
review_scores_location         11362
review_scores_value            11362
license                        31079
reviews_per_month              11346
dtype: int64

In [6]:
# Drop columns with more than 15,000 missing values
airbnb = airbnb.dropna(axis=1, thresh=len(airbnb) - 15000)

In [7]:
# Clean Columns

# Change last_review column to datetime 
today = pd.Timestamp.today()
#today = pd.Timestamp(datetime.today().date())
airbnb["last_review"] = pd.to_datetime(airbnb["last_review"], errors="coerce")
 
# Calculate number of days since the listing was last reviewed, if listing has no review, fill with 9999
airbnb["days_since_last_review"] = (today - airbnb["last_review"]).dt.days.fillna(9999)
 
# Clean price column and turn into float
airbnb["price"] = (
    airbnb["price"]
    .astype(str)
    .str.replace(r"[\$,]", "", regex=True)
    .pipe(pd.to_numeric, errors="coerce")
)
 
# Fill NaN values with 0
airbnb["reviews_per_month"] = airbnb["reviews_per_month"].fillna(0)

# Map binary columns, 1 = t, 0 = f or NaN
airbnb['host_identity_verified'] = (airbnb['host_identity_verified'] == "t").astype(int)
airbnb['host_has_profile_pic'] = (airbnb['host_has_profile_pic'] == "t").astype(int)

## Determine which listings are ghost listings

In [8]:
# Create conditions to classify ghost listing
high_avail = airbnb["availability_365"] >= 180
high_min_nights = airbnb["minimum_nights"] >= 180
num_since_lr = airbnb["days_since_last_review"] >= 180
airbnb["price_percentile"] = airbnb.groupby(["neighbourhood_cleansed", "room_type"])["price"].rank(pct=True)
low_price = airbnb['price_percentile'] < 0.05
sus_host = (airbnb['host_identity_verified'] == 0) & (airbnb['host_has_profile_pic'] == 0)
 
# Assign each listing a score and label to determine if it is a ghost listing
airbnb["ghost_score"] = ( 
                         high_avail.astype(int) + 
                         high_min_nights.astype(int) + 
                         num_since_lr.astype(int) + 
                         low_price.astype(int) +
                         sus_host.astype(int))
 
def assign_label(score):
    if score > 2:
        return 1  # fake listing if ghost score is above 2
    elif score <= 2:
        return 0  # real listing if ghost score is equal or less than 2
 
airbnb["ghost_label"] = airbnb["ghost_score"].apply(assign_label)

counts = airbnb["ghost_label"].value_counts().rename({1: "ghost", 0: "real",})
total  = len(airbnb)

print(counts)
print(f'Total: {total}')

ghost_label
real     34707
ghost     1646
Name: count, dtype: int64
Total: 36353

In [9]:
# get info for clean data
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36353 entries, 0 to 36352
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            36353 non-null  int64
 1   listing_url                                   36353 non-null  object
 2   scrape_id                                     36353 non-null  int64
 3   last_scraped                                  36353 non-null  object
 4   source                                        36353 non-null  object
 5   name                                          36351 non-null  object
 6   description                                   35178 non-null  object
 7   picture_url                                   36353 non-null  object
 8   host_id                                       36353 non-null  int64
 9   host_url                                      36353 non-null  object
 10  host_name                                     34896 non-null  object
 11  host_since                                    34896 non-null  object
 12  host_location                                 27234 non-null  object
 13  host_is_superhost                             35899 non-null  object
 14  host_thumbnail_url                            34896 non-null  object
 15  host_picture_url                              34896 non-null  object
 16  host_neighbourhood                            27475 non-null  object
 17  host_listings_count                           34896 non-null  float64
 18  host_total_listings_count                     34896 non-null  float64
 19  host_verifications                            34896 non-null  object
 20  host_has_profile_pic                          36353 non-null  int64
 21  host_identity_verified                        36353 non-null  int64
 22  neighbourhood_cleansed                        36353 non-null  object
 23  neighbourhood_group_cleansed                  36353 non-null  object
 24  latitude                                      36353 non-null  float64
 25  longitude                                     36353 non-null  float64
 26  property_type                                 36353 non-null  object
 27  room_type                                     36353 non-null  object
 28  accommodates                                  36353 non-null  int64
 29  bathrooms                                     21703 non-null  float64
 30  bathrooms_text                                36238 non-null  object
 31  bedrooms                                      30273 non-null  float64
 32  beds                                          21658 non-null  float64
 33  amenities                                     36353 non-null  object
 34  price                                         21415 non-null  float64
 35  minimum_nights                                36353 non-null  int64
 36  maximum_nights                                36353 non-null  int64
 37  minimum_minimum_nights                        36350 non-null  float64
 38  maximum_minimum_nights                        36350 non-null  float64
 39  minimum_maximum_nights                        36350 non-null  float64
 40  maximum_maximum_nights                        36350 non-null  float64
 41  minimum_nights_avg_ntm                        36353 non-null  float64
 42  maximum_nights_avg_ntm                        36353 non-null  float64
 43  has_availability                              30725 non-null  object
 44  availability_30                               36353 non-null  int64
 45  availability_60                               36353 non-null  int64
 46  availability_90                               36353 non-null  int64
 47  availability_365                              36353 non-null  int64
 48  calendar_last_scraped                         36353 non-null  object
 49  number_of_reviews                             36353 non-null  int64
 50  number_of_reviews_ltm                         36353 non-null  int64
 51  number_of_reviews_l30d                        36353 non-null  int64
 52  availability_eoy                              36353 non-null  int64
 53  number_of_reviews_ly                          36353 non-null  int64
 54  estimated_occupancy_l365d                     36353 non-null  int64
 55  estimated_revenue_l365d                       21415 non-null  float64
 56  first_review                                  25007 non-null  object
 57  last_review                                   25007 non-null  datetime64[ns]
 58  review_scores_rating                          25007 non-null  float64
 59  review_scores_accuracy                        24997 non-null  float64
 60  review_scores_cleanliness                     25006 non-null  float64
 61  review_scores_checkin                         24993 non-null  float64
 62  review_scores_communication                   25001 non-null  float64
 63  review_scores_location                        24991 non-null  float64
 64  review_scores_value                           24991 non-null  float64
 65  instant_bookable                              36353 non-null  object
 66  calculated_host_listings_count                36353 non-null  int64
 67  calculated_host_listings_count_entire_homes   36353 non-null  int64
 68  calculated_host_listings_count_private_rooms  36353 non-null  int64
 69  calculated_host_listings_count_shared_rooms   36353 non-null  int64
 70  reviews_per_month                             36353 non-null  float64
 71  days_since_last_review                        36353 non-null  float64
 72  price_percentile                              21415 non-null  float64
 73  ghost_score                                   36353 non-null  int64
 74  ghost_label                                   36353 non-null  int64
dtypes: datetime64[ns](1), float64(25), int64(24), object(25)
memory usage: 20.8+ MB

In [10]:
# clean data
airbnb.head(5)

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,...,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,days_since_last_review,price_percentile,ghost_score,ghost_label
0,1274691077561855573,https://www.airbnb.com/rooms/1274691077561855573,20251101201932,2025-11-02,city scrape,Beautiful room for rent hosted by Svitlana,Cozy Room for Rent in a Two-Bedroom Apartment<...,https://a0.muscache.com/pictures/miso/Hosting-...,658783772,https://www.airbnb.com/users/show/658783772,...,f,1,0,1,0,1.62,183.0,1.000000,1,0
1,1274722590671904755,https://www.airbnb.com/rooms/1274722590671904755,20251101201932,2025-11-02,city scrape,Exquisite & Charming Studio in Prime Locations,This stylish place to stay is perfect for grou...,https://a0.muscache.com/pictures/hosting/Hosti...,458668555,https://www.airbnb.com/users/show/458668555,...,f,6,0,6,0,0.21,290.0,0.522500,1,0
2,1274773188072371454,https://www.airbnb.com/rooms/1274773188072371454,20251101201932,2025-11-02,city scrape,"Private 2 Bedroom Unit, Full Kitchen, Washer/D...",This stylish place to stay is perfect for trav...,https://a0.muscache.com/pictures/hosting/Hosti...,22369387,https://www.airbnb.com/users/show/22369387,...,f,3,2,1,0,0.00,9999.0,0.666667,2,0
3,1274820999428562667,https://www.airbnb.com/rooms/1274820999428562667,20251101201932,2025-11-02,city scrape,"Beautiful, Serene West Village Treehouse",Switch off in this serene one-bedroom oasis on...,https://a0.muscache.com/pictures/miso/Hosting-...,505544503,https://www.airbnb.com/users/show/505544503,...,f,1,1,0,0,0.00,9999.0,0.473934,2,0
4,1274826163511555978,https://www.airbnb.com/rooms/1274826163511555978,20251101201932,2025-11-02,city scrape,Renovated 1BR w/ Spa Shower,Newly renovated 1-bedroom oasis in vibrant Dow...,https://a0.muscache.com/pictures/miso/Hosting-...,493151605,https://www.airbnb.com/users/show/493151605,...,f,4,2,2,0,0.10,468.0,0.304878,2,0

## Save clean df to new CSV

In [11]:
airbnb.to_csv('airbnb_clean.csv')